name: gossips
favicon: null
layout_spectrum: 0.7164273278322071
typography_spectrum: 0.1339443272445351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7155444861855358
  lightness: 0.924270604737103
  saturation: 0.11789852706715465
  rhythmicContrast: 0.450793678406626
purpose: []
